parameters:
- name: imageTag
  type: string
  default: latest
- name: IsProd
  type: boolean
  default: false

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - 'v*.*.*'

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: innersource
- name: ImageTag
  value: ${{ parameters.imageTag }}
- name: IsProd
  value: ${{ or(eq(parameters.IsProd, true), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}

jobs:
- job: Deploy
  condition: and(succeeded(), eq(variables.IsProd, true))
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az containerapp secret set -n $(ContainerAppName) -g $(ResourceGroup) --secrets `
          appinsights="$(ApplicationInsightsConnectionString)" `
          devopspat=$(DevOpsPersonalAccessToken) `
          authkey=$(AuthenticationKey) `
          extcert=$(AzureDevOpsExtensionCertificate) `
          tableconnstring="$(TableStorageConnectionString)"

        az containerapp update -n $(ContainerAppName) -g $(ResourceGroup) --set-env-vars `
          ApplicationInsights__ConnectionString=secretref:appinsights `
          Authentication__Key=secretref:authkey `
          Authentication__Issuer=$(ServerUrl) `
          Authentication__Audience=$(ServerUrl) `
          Authentication__AzureDevOpsKey=secretref:extcert `
          DevOps__PersonalAccessToken=secretref:devopspat `
          DevOps__Organization=$(DevOpsOrganization) `
          RepositoryAggregation__BadgeServerUrl=$(ServerUrl) `
          Storage__Mode=TableStorage `
          Storage__TableStorageConnectionString=secretref:tableconnstring `
          ASPNETCORE_FORWARDEDHEADERS_ENABLED=true

    displayName: set app secrets and environment variables
  
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: $(AzureSubscription)
      containerAppName: $(ContainerAppName)
      resourceGroup: $(ResourceGroup)
      imageToDeploy: 'ghcr.io/dizco/azuredevops.innersource:$(ImageTag)'
    displayName: deploy azure container app